# rag_graph.py

from langchain_chroma import Chroma
from langchain_core.documents import Document
from langgraph.graph import StateGraph
from typing import TypedDict, Annotated, List
import hashlib

# --- Dummy embedding (384-dim) ---
def dummy_embedding(text: str) -> List[float]:
    h = hashlib.md5(text.encode()).hexdigest()
    padded = (h * 12)[:384]
    return [int(padded[i : i + 2], 16) / 255.0 for i in range(0, 384, 2)]

class DummyEmbeddings:
    def embed_documents(self, texts: List[str]) -> List[List[float]]:
        return [dummy_embedding(t) for t in texts]

    def embed_query(self, text: str) -> List[float]:
        return dummy_embedding(text)

# --- 1. Embeddings + Chroma DB ---
embeddings = DummyEmbeddings()

db = Chroma(
    collection_name="support_kb",
    persist_directory="./chroma_db",
    embedding_function=embeddings
)

retriever = db.as_retriever(search_kwargs={"k": 4})

# --- 2. State (LangGraph) ---
class GraphState(TypedDict):
    query: str
    chunks: Annotated[List[Document], "retrieved chunks"]
    answer: str
    confidence: float
    needs_hitl: bool

# --- 3. HITL queue ---
class HitlEntry:
    def __init__(self, query: str, chunks: List[Document], initial_answer: str):
        self.query = query
        self.chunks = chunks
        self.initial_answer = initial_answer
        self.resolved = False
        self.human_response = ""

hitl_queue: List[HitlEntry] = []

# --- 4. Processing Node ---
def process_node(state: GraphState) -> GraphState:
    query = state["query"]
    chunks = retriever.invoke(query)

    print("\n--- Retrieved chunks from manual ---")
    if not chunks:
        print("No chunks found in Chroma DB. This is expected with dummy embeddings.")
    else:
        for i, c in enumerate(chunks):
            print(f"[{i}] {c.page_content[:200]}...")
    print("--- End of chunks ---\n")

    # 1. Hardcoded example answers for Samsung
    if "model number" in query.lower():
        answer = (
            "(Demo) The Samsung mobile model mentioned in this manual is:\n"
            "Samsung Galaxy M34 5G (Model: SM‑M346BZ/DS).\n"
            "It supports 5G networks and has a 6.5‑inch Super AMOLED display."
        )
        confidence = 0.9
        needs_hitl = False
    elif "features" in query.lower():
        answer = (
            "(Demo) The Samsung mobile model has these key features:\n"
            "- 6.5‑inch Full HD+ Super AMOLED display\n"
            "- Octa‑core processor\n"
            "- 5000mAh battery with 18W fast charging\n"
            "- 50MP main camera, 8MP ultra‑wide, 2MP macro\n"
            "- Android 13 with One UI 5.1"
        )
        confidence = 0.8
        needs_hitl = False
    elif "warranty" in query.lower():
        answer = (
            "(Demo) The Samsung mobile is covered by a standard 1‑year limited warranty.\n"
            "It covers defects in materials and workmanship but not physical damage.\n"
            "For extended warranty or accidental damage, contact the support center."
        )
        confidence = 0.8
        needs_hitl = False
    elif "refund policy" in query.lower():
        answer = (
            "(Demo) The refund policy for this Samsung mobile is:\n"
            "You can return the device within 7 days of purchase if it is unused and in original packaging.\n"
            "After 7 days, returns are accepted only if the device has a manufacturing defect."
        )
        confidence = 0.8
        needs_hitl = False

    # 2. For any other query, default to generic demo answer
    else:
        if not chunks:
            answer = f"(Demo) I couldn't find relevant info in the Samsung manual for: {query}"
            confidence = 0.2
            # Only escalate explicit sensitive words, not everything
            needs_hitl = False
        else:
            answer = f"(Demo) For your query: {query}\n\n"
            answer += "I found relevant chunks in the Samsung manual, but this is a demo\n"
            answer += "so the answer is not generated by an LLM; it will be in production."
            confidence = 0.7

            sensitive_words = ["legal", "complaint", "refund", "policy", "escalate"]
            if any(word.lower() in query.lower() for word in sensitive_words):
                needs_hitl = True
            else:
                needs_hitl = False

    return {
        "query": query,
        "chunks": chunks,
        "answer": answer,
        "confidence": confidence,
        "needs_hitl": needs_hitl,
    }

# --- 5. Output Node ---
def output_node(state: GraphState) -> GraphState:
    query = state["query"]
    chunks = state["chunks"]
    answer = state["answer"]
    needs_hitl = state["needs_hitl"]

    if needs_hitl:
        hitl_entry = HitlEntry(
            query=query,
            chunks=chunks,
            initial_answer=answer
        )
        hitl_queue.append(hitl_entry)
        final_answer = "Your query has been escalated to a human agent. We will respond shortly."
    else:
        final_answer = answer

    return {
        "query": query,
        "chunks": chunks,
        "answer": final_answer,
        "confidence": state["confidence"],
        "needs_hitl": needs_hitl,
    }

# --- 6. Build LangGraph (2‑node: Process → Output) ---
workflow = StateGraph(GraphState)

workflow.add_node("process", process_node)
workflow.add_node("output", output_node)

workflow.set_entry_point("process")

workflow.add_edge("process", "output")

graph = workflow.compile()

# --- 7. CLI Helper ---
def ask(query: str) -> str:
    result = graph.invoke({"query": query})
    print("Answer:", result["answer"])
    if result["needs_hitl"]:
        print("(Escalated to HITL)")
    return result["answer"]

if __name__ == "__main__":
    while True:
        q = input("Question: ")
        if q.lower() in ["quit", "exit"]:
            break
        ask(q)